// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMyClientsData, GetMyClientsResponses, LoginAccessTokenData, LoginAccessTokenErrors, LoginAccessTokenResponses, LogoutData, LogoutResponses, ReadCurrentUserData, ReadCurrentUserResponses, RegisterClientData, RegisterClientErrors, RegisterClientResponses, RegisterUserData, RegisterUserErrors, RegisterUserResponses, VerifyTokenData, VerifyTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login Access Token
 */
export const loginAccessToken = <ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenData, ThrowOnError>) => (options.client ?? client).post<LoginAccessTokenResponses, LoginAccessTokenErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Current User
 */
export const readCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<ReadCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<ReadCurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/users/me',
    ...options
});

/**
 * Register User
 */
export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>({
    url: '/auth/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Verify Token
 */
export const verifyToken = <ThrowOnError extends boolean = false>(options?: Options<VerifyTokenData, ThrowOnError>) => (options?.client ?? client).get<VerifyTokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/verify',
    ...options
});

/**
 * Register Client
 */
export const registerClient = <ThrowOnError extends boolean = false>(options: Options<RegisterClientData, ThrowOnError>) => (options.client ?? client).post<RegisterClientResponses, RegisterClientErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clients/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get My Clients
 */
export const getMyClients = <ThrowOnError extends boolean = false>(options?: Options<GetMyClientsData, ThrowOnError>) => (options?.client ?? client).get<GetMyClientsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clients/my',
    ...options
});
