// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AdminKeyDisplay
 */
export type AdminKeyDisplay = {
    /**
     * Plain Key
     */
    plain_key: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * AdminKeyLoginRequest
 */
export type AdminKeyLoginRequest = {
    /**
     * Client Public Id
     */
    client_public_id: string;
    /**
     * Admin Key
     */
    admin_key: string;
};

/**
 * AdminKeyStatus
 */
export type AdminKeyStatus = {
    /**
     * Has Key
     */
    has_key: boolean;
};

/**
 * AutoSaveRequest
 */
export type AutoSaveRequest = {
    /**
     * Fingerprint
     */
    fingerprint: string;
    /**
     * Tokens
     */
    tokens: Array<string>;
    /**
     * Page Url
     */
    page_url?: string | null;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * History
     */
    history?: Array<ChatMessage> | null;
    /**
     * Page Text
     */
    page_text?: string;
    /**
     * Elements
     */
    elements?: string;
    /**
     * Page Url
     */
    page_url?: string | null;
    /**
     * Screen Label
     */
    screen_label?: string | null;
    /**
     * Screen Fingerprint
     */
    screen_fingerprint?: string | null;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Action
     */
    action?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Client
 */
export type Client = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Public Id
     */
    public_id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Allowed Domains
     */
    allowed_domains: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Admin Key Hash
     */
    admin_key_hash?: string | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * ClientRegisterRequest
 */
export type ClientRegisterRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Domains
     */
    domains: string;
};

/**
 * ClientUpdate
 */
export type ClientUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Domains
     */
    domains?: string | null;
};

/**
 * ConfirmRequest
 */
export type ConfirmRequest = {
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MatchScreenRequest
 */
export type MatchScreenRequest = {
    /**
     * Fingerprint
     */
    fingerprint: string;
};

/**
 * MatchScreenResponse
 */
export type MatchScreenResponse = {
    /**
     * Matched
     */
    matched: boolean;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * SaveScreenRequest
 */
export type SaveScreenRequest = {
    /**
     * Fingerprint
     */
    fingerprint: string;
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Page Url
     */
    page_url?: string | null;
};

/**
 * SuggestNameRequest
 */
export type SuggestNameRequest = {
    /**
     * Tokens
     */
    tokens: Array<string>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WidgetLoginData = {
    body: AdminKeyLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login/widget';
};

export type WidgetLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WidgetLoginError = WidgetLoginErrors[keyof WidgetLoginErrors];

export type WidgetLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/users/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/users/';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyTokenResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyTokenResponse = VerifyTokenResponses[keyof VerifyTokenResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/status';
};

export type GetStatusResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type RegisterClientData = {
    body: ClientRegisterRequest;
    path?: never;
    query?: never;
    url: '/clients/register';
};

export type RegisterClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterClientError = RegisterClientErrors[keyof RegisterClientErrors];

export type RegisterClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/my';
};

export type GetMyClientsResponses = {
    /**
     * Response Get My Clients
     *
     * Successful Response
     */
    200: Array<Client>;
};

export type GetMyClientsResponse = GetMyClientsResponses[keyof GetMyClientsResponses];

export type DeleteClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type DeleteClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors];

export type DeleteClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateClientData = {
    body: ClientUpdate;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type UpdateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors];

export type UpdateClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateAdminKeyData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}/keys';
};

export type GenerateAdminKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAdminKeyError = GenerateAdminKeyErrors[keyof GenerateAdminKeyErrors];

export type GenerateAdminKeyResponses = {
    /**
     * Successful Response
     */
    200: AdminKeyDisplay;
};

export type GenerateAdminKeyResponse = GenerateAdminKeyResponses[keyof GenerateAdminKeyResponses];

export type GetAdminKeyStatusData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}/keys/status';
};

export type GetAdminKeyStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdminKeyStatusError = GetAdminKeyStatusErrors[keyof GetAdminKeyStatusErrors];

export type GetAdminKeyStatusResponses = {
    /**
     * Successful Response
     */
    200: AdminKeyStatus;
};

export type GetAdminKeyStatusResponse = GetAdminKeyStatusResponses[keyof GetAdminKeyStatusResponses];

export type ChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/v1/chat';
};

export type ChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatError = ChatErrors[keyof ChatErrors];

export type ChatResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatResponse2 = ChatResponses[keyof ChatResponses];

export type MatchScreenData = {
    body: MatchScreenRequest;
    path?: never;
    query?: never;
    url: '/v1/training/match-screen';
};

export type MatchScreenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MatchScreenError = MatchScreenErrors[keyof MatchScreenErrors];

export type MatchScreenResponses = {
    /**
     * Successful Response
     */
    200: MatchScreenResponse;
};

export type MatchScreenResponse2 = MatchScreenResponses[keyof MatchScreenResponses];

export type SaveScreenContextData = {
    body: SaveScreenRequest;
    path?: never;
    query?: {
        /**
         * Client Id
         */
        client_id?: string;
    };
    url: '/v1/training/save-screen-context';
};

export type SaveScreenContextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveScreenContextError = SaveScreenContextErrors[keyof SaveScreenContextErrors];

export type SaveScreenContextResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AutoSaveData = {
    body: AutoSaveRequest;
    path?: never;
    query?: never;
    url: '/v1/training/auto-save';
};

export type AutoSaveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AutoSaveError = AutoSaveErrors[keyof AutoSaveErrors];

export type AutoSaveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SuggestNameData = {
    body: SuggestNameRequest;
    path?: never;
    query?: never;
    url: '/v1/training/suggest-name';
};

export type SuggestNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestNameError = SuggestNameErrors[keyof SuggestNameErrors];

export type SuggestNameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfirmScreenData = {
    body: ConfirmRequest;
    path: {
        /**
         * Screen Id
         */
        screen_id: string;
    };
    query?: never;
    url: '/v1/training/confirm/{screen_id}';
};

export type ConfirmScreenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmScreenError = ConfirmScreenErrors[keyof ConfirmScreenErrors];

export type ConfirmScreenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
