// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChatData, ChatErrors, ChatResponses, ConfirmScreenBearerData, ConfirmScreenBearerErrors, ConfirmScreenBearerResponses, DashboardConfirmScreenData, DashboardConfirmScreenErrors, DashboardConfirmScreenResponses, DashboardGetClientsData, DashboardGetClientsResponses, DashboardListScreensData, DashboardListScreensErrors, DashboardListScreensResponses, DeleteClientData, DeleteClientErrors, DeleteClientResponses, DiscoverScreenData, DiscoverScreenErrors, DiscoverScreenResponses, ExecuteStepData, ExecuteStepErrors, ExecuteStepResponses, FixA11yMarkupData, FixA11yMarkupErrors, FixA11yMarkupResponses, GenerateAdminKeyData, GenerateAdminKeyErrors, GenerateAdminKeyResponses, GeneratePlanData, GeneratePlanErrors, GeneratePlanResponses, GetAdminKeyStatusData, GetAdminKeyStatusErrors, GetAdminKeyStatusResponses, GetMyClientsData, GetMyClientsResponses, GetMyMetricsData, GetMyMetricsResponses, GetStatusData, GetStatusResponses, ListScreensBearerData, ListScreensBearerErrors, ListScreensBearerResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, MatchScreenData, MatchScreenErrors, MatchScreenResponses, MeData, MeResponses, RegisterClientData, RegisterClientErrors, RegisterClientResponses, RegisterData, RegisterErrors, RegisterResponses, SimplifyA11yTextData, SimplifyA11yTextErrors, SimplifyA11yTextResponses, SuggestNameData, SuggestNameErrors, SuggestNameResponses, TranscribeAudioData, TranscribeAudioErrors, TranscribeAudioResponses, UpdateClientData, UpdateClientErrors, UpdateClientResponses, VerifyTokenData, VerifyTokenResponses, VerifyWidgetTokenData, VerifyWidgetTokenResponses, WidgetLoginData, WidgetLoginErrors, WidgetLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Auth {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Widget Login
     *
     * Login for the Bariweb Widget using an Admin Key.
     * Verifies the key against the organizations admin_key_hash.
     */
    public static widgetLogin<ThrowOnError extends boolean = false>(options: Options<WidgetLoginData, ThrowOnError>) {
        return (options.client ?? client).post<WidgetLoginResponses, WidgetLoginErrors, ThrowOnError>({
            url: '/auth/login/widget',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Verify Widget Token
     *
     * Verifies that a widget admin Bearer token is still valid.
     * Used by the widget on page reload to restore admin session without re-login.
     * Returns 200 OK with client_id if valid, 401 if not.
     */
    public static verifyWidgetToken<ThrowOnError extends boolean = false>(options?: Options<VerifyWidgetTokenData, ThrowOnError>) {
        return (options?.client ?? client).get<VerifyWidgetTokenResponses, unknown, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/login/widget/verify',
            ...options
        });
    }
    
    /**
     * Me
     */
    public static me<ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) {
        return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/users/me',
            ...options
        });
    }
    
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
            url: '/auth/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });
    }
    
    /**
     * Verify Token
     */
    public static verifyToken<ThrowOnError extends boolean = false>(options?: Options<VerifyTokenData, ThrowOnError>) {
        return (options?.client ?? client).get<VerifyTokenResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/verify',
            ...options
        });
    }
    
    /**
     * Get Status
     *
     * Keep /status for compatibility with SDK calls if needed
     */
    public static getStatus<ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/status',
            ...options
        });
    }
}

export class Organizations {
    /**
     * Register Client
     */
    public static registerClient<ThrowOnError extends boolean = false>(options: Options<RegisterClientData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterClientResponses, RegisterClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get My Clients
     */
    public static getMyClients<ThrowOnError extends boolean = false>(options?: Options<GetMyClientsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetMyClientsResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/my',
            ...options
        });
    }
    
    /**
     * Delete Client
     */
    public static deleteClient<ThrowOnError extends boolean = false>(options: Options<DeleteClientData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteClientResponses, DeleteClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}',
            ...options
        });
    }
    
    /**
     * Update Client
     */
    public static updateClient<ThrowOnError extends boolean = false>(options: Options<UpdateClientData, ThrowOnError>) {
        return (options.client ?? client).patch<UpdateClientResponses, UpdateClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Generate Admin Key
     */
    public static generateAdminKey<ThrowOnError extends boolean = false>(options: Options<GenerateAdminKeyData, ThrowOnError>) {
        return (options.client ?? client).post<GenerateAdminKeyResponses, GenerateAdminKeyErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}/keys',
            ...options
        });
    }
    
    /**
     * Get Admin Key Status
     */
    public static getAdminKeyStatus<ThrowOnError extends boolean = false>(options: Options<GetAdminKeyStatusData, ThrowOnError>) {
        return (options.client ?? client).get<GetAdminKeyStatusResponses, GetAdminKeyStatusErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}/keys/status',
            ...options
        });
    }
    
    /**
     * Get My Metrics
     */
    public static getMyMetrics<ThrowOnError extends boolean = false>(options?: Options<GetMyMetricsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetMyMetricsResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/my/metrics',
            ...options
        });
    }
}

export class Chat {
    /**
     * Chat
     *
     * Main chat endpoint. Validates widget origin, retrieves context from Milvus,
     * calls Qwen3, and returns a structured { text, action } response.
     */
    public static chat<ThrowOnError extends boolean = false>(options: Options<ChatData, ThrowOnError>) {
        return (options.client ?? client).post<ChatResponses, ChatErrors, ThrowOnError>({
            url: '/v1/chat',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Fix A11Y Markup
     *
     * Receives broken HTML snippets (missing alt, missing aria-labels),
     * asks LLM for fixes, and returns a JSON patch array.
     */
    public static fixA11yMarkup<ThrowOnError extends boolean = false>(options: Options<FixA11yMarkupData, ThrowOnError>) {
        return (options.client ?? client).post<FixA11yMarkupResponses, FixA11yMarkupErrors, ThrowOnError>({
            url: '/v1/widget/a11y/fix',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Simplify A11Y Text
     *
     * Rewrites complex text into Plain/B1 language for cognitive accessibility.
     */
    public static simplifyA11yText<ThrowOnError extends boolean = false>(options: Options<SimplifyA11yTextData, ThrowOnError>) {
        return (options.client ?? client).post<SimplifyA11yTextResponses, SimplifyA11yTextErrors, ThrowOnError>({
            url: '/v1/widget/a11y/simplify',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Transcribe Audio
     *
     * STT endpoint for widget voice input.
     * Validates widget origin/client via existing auth dependency.
     */
    public static transcribeAudio<ThrowOnError extends boolean = false>(options: Options<TranscribeAudioData, ThrowOnError>) {
        return (options.client ?? client).post<TranscribeAudioResponses, TranscribeAudioErrors, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/v1/stt/transcribe',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class A11Y {
    /**
     * Chat
     *
     * Main chat endpoint. Validates widget origin, retrieves context from Milvus,
     * calls Qwen3, and returns a structured { text, action } response.
     */
    public static chat<ThrowOnError extends boolean = false>(options: Options<ChatData, ThrowOnError>) {
        return (options.client ?? client).post<ChatResponses, ChatErrors, ThrowOnError>({
            url: '/v1/chat',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Fix A11Y Markup
     *
     * Receives broken HTML snippets (missing alt, missing aria-labels),
     * asks LLM for fixes, and returns a JSON patch array.
     */
    public static fixA11yMarkup<ThrowOnError extends boolean = false>(options: Options<FixA11yMarkupData, ThrowOnError>) {
        return (options.client ?? client).post<FixA11yMarkupResponses, FixA11yMarkupErrors, ThrowOnError>({
            url: '/v1/widget/a11y/fix',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Simplify A11Y Text
     *
     * Rewrites complex text into Plain/B1 language for cognitive accessibility.
     */
    public static simplifyA11yText<ThrowOnError extends boolean = false>(options: Options<SimplifyA11yTextData, ThrowOnError>) {
        return (options.client ?? client).post<SimplifyA11yTextResponses, SimplifyA11yTextErrors, ThrowOnError>({
            url: '/v1/widget/a11y/simplify',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Transcribe Audio
     *
     * STT endpoint for widget voice input.
     * Validates widget origin/client via existing auth dependency.
     */
    public static transcribeAudio<ThrowOnError extends boolean = false>(options: Options<TranscribeAudioData, ThrowOnError>) {
        return (options.client ?? client).post<TranscribeAudioResponses, TranscribeAudioErrors, ThrowOnError>({
            ...formDataBodySerializer,
            url: '/v1/stt/transcribe',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class Training {
    /**
     * Discover Screen
     *
     * Called by BariwebWatcher on every screen change.
     * Creates a draft if fingerprint is new, returns existing data if known.
     */
    public static discoverScreen<ThrowOnError extends boolean = false>(options: Options<DiscoverScreenData, ThrowOnError>) {
        return (options.client ?? client).post<DiscoverScreenResponses, DiscoverScreenErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/discover',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Screens Bearer
     *
     * Widget admin Bearer token: list screens.
     */
    public static listScreensBearer<ThrowOnError extends boolean = false>(options?: Options<ListScreensBearerData, ThrowOnError>) {
        return (options?.client ?? client).get<ListScreensBearerResponses, ListScreensBearerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/screens',
            ...options
        });
    }
    
    /**
     * Confirm Screen Bearer
     *
     * Widget admin Bearer token: confirm a draft + index to Milvus.
     */
    public static confirmScreenBearer<ThrowOnError extends boolean = false>(options: Options<ConfirmScreenBearerData, ThrowOnError>) {
        return (options.client ?? client).patch<ConfirmScreenBearerResponses, ConfirmScreenBearerErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/confirm/{screen_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Match Screen
     *
     * Public: match fingerprint for user-facing chat context. Only returns confirmed screens.
     */
    public static matchScreen<ThrowOnError extends boolean = false>(options: Options<MatchScreenData, ThrowOnError>) {
        return (options.client ?? client).post<MatchScreenResponses, MatchScreenErrors, ThrowOnError>({
            url: '/v1/training/match-screen',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Suggest Name
     */
    public static suggestName<ThrowOnError extends boolean = false>(options: Options<SuggestNameData, ThrowOnError>) {
        return (options.client ?? client).post<SuggestNameResponses, SuggestNameErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/suggest-name',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Dashboard Get Clients
     *
     * Returns all clients owned by this dashboard user.
     * Used by the Training page to build the domain selector.
     */
    public static dashboardGetClients<ThrowOnError extends boolean = false>(options?: Options<DashboardGetClientsData, ThrowOnError>) {
        return (options?.client ?? client).get<DashboardGetClientsResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/v1/training/dashboard/clients',
            ...options
        });
    }
    
    /**
     * Dashboard List Screens
     *
     * Dashboard: list screens for a specific client (by public_id).
     * If client_public_id not given, uses the primary client from the session.
     */
    public static dashboardListScreens<ThrowOnError extends boolean = false>(options?: Options<DashboardListScreensData, ThrowOnError>) {
        return (options?.client ?? client).get<DashboardListScreensResponses, DashboardListScreensErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/v1/training/dashboard/screens',
            ...options
        });
    }
    
    /**
     * Dashboard Confirm Screen
     *
     * Dashboard: confirm a draft + index to Milvus.
     */
    public static dashboardConfirmScreen<ThrowOnError extends boolean = false>(options: Options<DashboardConfirmScreenData, ThrowOnError>) {
        return (options.client ?? client).patch<DashboardConfirmScreenResponses, DashboardConfirmScreenErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/v1/training/dashboard/confirm/{screen_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Agent {
    /**
     * Generate Plan
     *
     * Generate or retrieve an Action Plan based on user goal and page context.
     * Uses Postgres as a caching layer to avoid redundant LLM calls.
     */
    public static generatePlan<ThrowOnError extends boolean = false>(options: Options<GeneratePlanData, ThrowOnError>) {
        return (options.client ?? client).post<GeneratePlanResponses, GeneratePlanErrors, ThrowOnError>({
            url: '/v1/agent/plan',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Execute Step
     *
     * Execute a step.
     * For sensitive actions (submit, payment) or final steps, checks idempotency using request_id.
     * Requires `confirm=true` query param to bypass confirmation block for sensitive actions.
     */
    public static executeStep<ThrowOnError extends boolean = false>(options: Options<ExecuteStepData, ThrowOnError>) {
        return (options.client ?? client).post<ExecuteStepResponses, ExecuteStepErrors, ThrowOnError>({
            url: '/v1/agent/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
