// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMyClientsData, GetMyClientsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, MeData, MeResponses, RegisterClientData, RegisterClientErrors, RegisterClientResponses, RegisterData, RegisterErrors, RegisterResponses, UpdateClientData, VerifyTokenData, VerifyTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Auth {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Me
     */
    public static me<ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) {
        return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/users/me',
            ...options
        });
    }
    
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
            url: '/auth/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });
    }
    
    /**
     * Verify Token
     */
    public static verifyToken<ThrowOnError extends boolean = false>(options?: Options<VerifyTokenData, ThrowOnError>) {
        return (options?.client ?? client).get<VerifyTokenResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/verify',
            ...options
        });
    }
}

export class Organizations {
    /**
     * Register Client
     */
    public static registerClient<ThrowOnError extends boolean = false>(options: Options<RegisterClientData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterClientResponses, RegisterClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get My Clients
     */
    public static getMyClients<ThrowOnError extends boolean = false>(options?: Options<GetMyClientsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetMyClientsResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/my',
            ...options
        });
    }
    
    /**
     * Update Client
     */
    public static updateClient<ThrowOnError extends boolean = false>(options: Options<UpdateClientData, ThrowOnError>) {
        return (options.client ?? client).patch<any, any, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
