// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AutoSaveData, AutoSaveErrors, AutoSaveResponses, ChatData, ChatErrors, ChatResponses, ConfirmScreenData, ConfirmScreenErrors, ConfirmScreenResponses, DeleteClientData, DeleteClientErrors, DeleteClientResponses, GenerateAdminKeyData, GenerateAdminKeyErrors, GenerateAdminKeyResponses, GetAdminKeyStatusData, GetAdminKeyStatusErrors, GetAdminKeyStatusResponses, GetMyClientsData, GetMyClientsResponses, GetStatusData, GetStatusResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, MatchScreenData, MatchScreenErrors, MatchScreenResponses, MeData, MeResponses, RegisterClientData, RegisterClientErrors, RegisterClientResponses, RegisterData, RegisterErrors, RegisterResponses, SaveScreenContextData, SaveScreenContextErrors, SaveScreenContextResponses, SuggestNameData, SuggestNameErrors, SuggestNameResponses, UpdateClientData, UpdateClientErrors, UpdateClientResponses, VerifyTokenData, VerifyTokenResponses, WidgetLoginData, WidgetLoginErrors, WidgetLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Auth {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
            url: '/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Widget Login
     *
     * Login for the Bariweb Widget using an Admin Key.
     * Verifies the key against the organizations admin_key_hash.
     */
    public static widgetLogin<ThrowOnError extends boolean = false>(options: Options<WidgetLoginData, ThrowOnError>) {
        return (options.client ?? client).post<WidgetLoginResponses, WidgetLoginErrors, ThrowOnError>({
            url: '/auth/login/widget',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Me
     */
    public static me<ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) {
        return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/users/me',
            ...options
        });
    }
    
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
            url: '/auth/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });
    }
    
    /**
     * Verify Token
     */
    public static verifyToken<ThrowOnError extends boolean = false>(options?: Options<VerifyTokenData, ThrowOnError>) {
        return (options?.client ?? client).get<VerifyTokenResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/verify',
            ...options
        });
    }
    
    /**
     * Get Status
     *
     * Keep /status for compatibility with SDK calls if needed
     */
    public static getStatus<ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/auth/status',
            ...options
        });
    }
}

export class Organizations {
    /**
     * Register Client
     */
    public static registerClient<ThrowOnError extends boolean = false>(options: Options<RegisterClientData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterClientResponses, RegisterClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get My Clients
     */
    public static getMyClients<ThrowOnError extends boolean = false>(options?: Options<GetMyClientsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetMyClientsResponses, unknown, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/my',
            ...options
        });
    }
    
    /**
     * Delete Client
     */
    public static deleteClient<ThrowOnError extends boolean = false>(options: Options<DeleteClientData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteClientResponses, DeleteClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}',
            ...options
        });
    }
    
    /**
     * Update Client
     */
    public static updateClient<ThrowOnError extends boolean = false>(options: Options<UpdateClientData, ThrowOnError>) {
        return (options.client ?? client).patch<UpdateClientResponses, UpdateClientErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Generate Admin Key
     */
    public static generateAdminKey<ThrowOnError extends boolean = false>(options: Options<GenerateAdminKeyData, ThrowOnError>) {
        return (options.client ?? client).post<GenerateAdminKeyResponses, GenerateAdminKeyErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}/keys',
            ...options
        });
    }
    
    /**
     * Get Admin Key Status
     */
    public static getAdminKeyStatus<ThrowOnError extends boolean = false>(options: Options<GetAdminKeyStatusData, ThrowOnError>) {
        return (options.client ?? client).get<GetAdminKeyStatusResponses, GetAdminKeyStatusErrors, ThrowOnError>({
            security: [{
                    in: 'cookie',
                    name: 'access_token',
                    type: 'apiKey'
                }],
            url: '/clients/{client_id}/keys/status',
            ...options
        });
    }
}

export class Chat {
    /**
     * Chat
     *
     * Main chat endpoint. Validates widget origin, retrieves context from Milvus,
     * calls Qwen3, and returns a structured { text, action } response.
     */
    public static chat<ThrowOnError extends boolean = false>(options: Options<ChatData, ThrowOnError>) {
        return (options.client ?? client).post<ChatResponses, ChatErrors, ThrowOnError>({
            url: '/v1/chat',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Training {
    /**
     * Match Screen
     *
     * Called by the SDK Admin UI to check if a screen is already trained.
     */
    public static matchScreen<ThrowOnError extends boolean = false>(options: Options<MatchScreenData, ThrowOnError>) {
        return (options.client ?? client).get<MatchScreenResponses, MatchScreenErrors, ThrowOnError>({ url: '/v1/training/match-screen', ...options });
    }
    
    /**
     * Save Screen Context
     *
     * Protected Admin endpoint: Saves/Updates a screen annotation.
     * Note: Admin must provide/resolve the client_id they are training for.
     */
    public static saveScreenContext<ThrowOnError extends boolean = false>(options: Options<SaveScreenContextData, ThrowOnError>) {
        return (options.client ?? client).post<SaveScreenContextResponses, SaveScreenContextErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/save-screen-context',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Auto Save
     *
     * Experimental: Auto-saves a draft fingerprint while admin navigates.
     */
    public static autoSave<ThrowOnError extends boolean = false>(options: Options<AutoSaveData, ThrowOnError>) {
        return (options.client ?? client).post<AutoSaveResponses, AutoSaveErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/auto-save',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Suggest Name
     *
     * Uses LLM to suggest a screen name based on button tokens.
     */
    public static suggestName<ThrowOnError extends boolean = false>(options: Options<SuggestNameData, ThrowOnError>) {
        return (options.client ?? client).post<SuggestNameResponses, SuggestNameErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/suggest-name',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Confirm Screen
     *
     * Moderation: Confirms a draft and updates its label/description.
     */
    public static confirmScreen<ThrowOnError extends boolean = false>(options: Options<ConfirmScreenData, ThrowOnError>) {
        return (options.client ?? client).patch<ConfirmScreenResponses, ConfirmScreenErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/v1/training/confirm/{screen_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
