// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ClientRegisterRequest
 */
export type ClientRegisterRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Domains
     */
    domains: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginAccessTokenData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenError = LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenResponse = LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type ReadCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/users/me';
};

export type ReadCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadCurrentUserResponse = ReadCurrentUserResponses[keyof ReadCurrentUserResponses];

export type RegisterUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/users/';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyTokenResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyTokenResponse = VerifyTokenResponses[keyof VerifyTokenResponses];

export type RegisterClientData = {
    body: ClientRegisterRequest;
    path?: never;
    query?: never;
    url: '/clients/register';
};

export type RegisterClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterClientError = RegisterClientErrors[keyof RegisterClientErrors];

export type RegisterClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/my';
};

export type GetMyClientsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
