// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ClientRegisterRequest
 */
export type ClientRegisterRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Domains
     */
    domains: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/users/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/users/';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyTokenResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyTokenResponse = VerifyTokenResponses[keyof VerifyTokenResponses];

export type RegisterClientData = {
    body: ClientRegisterRequest;
    path?: never;
    query?: never;
    url: '/clients/register';
};

export type RegisterClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterClientError = RegisterClientErrors[keyof RegisterClientErrors];

export type RegisterClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/my';
};

export type GetMyClientsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateClientData = {
    body: {
        name?: string;
        domains?: string;
    };
    path: {
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}';
};
