// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * A11yBrokenElement
 */
export type A11yBrokenElement = {
    /**
     * Id
     */
    id: string;
    /**
     * Html
     */
    html: string;
};

/**
 * A11yFixRequest
 */
export type A11yFixRequest = {
    /**
     * Elements
     */
    elements: Array<A11yBrokenElement>;
};

/**
 * A11yPatch
 */
export type A11yPatch = {
    /**
     * Id
     */
    id: string;
    /**
     * Attribute
     */
    attribute: string;
    /**
     * Value
     */
    value: string;
};

/**
 * A11ySimplifyRequest
 */
export type A11ySimplifyRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * A11ySimplifyResponse
 */
export type A11ySimplifyResponse = {
    /**
     * Text
     */
    text: string;
};

/**
 * ActionPlan
 */
export type ActionPlan = {
    /**
     * Url
     */
    url: string;
    /**
     * Goal
     */
    goal: string;
    /**
     * Steps
     */
    steps: Array<ActionStep>;
};

/**
 * ActionStep
 */
export type ActionStep = {
    /**
     * Type
     */
    type: 'read' | 'click' | 'input' | 'submit' | 'navigation';
    /**
     * Selector
     */
    selector: string;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Description
     */
    description: string;
};

/**
 * AdminKeyDisplay
 */
export type AdminKeyDisplay = {
    /**
     * Plain Key
     */
    plain_key: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * AdminKeyLoginRequest
 */
export type AdminKeyLoginRequest = {
    /**
     * Client Public Id
     */
    client_public_id: string;
    /**
     * Admin Key
     */
    admin_key: string;
};

/**
 * AdminKeyStatus
 */
export type AdminKeyStatus = {
    /**
     * Has Key
     */
    has_key: boolean;
};

/**
 * Body_transcribe_audio
 */
export type BodyTranscribeAudio = {
    /**
     * Language Mode
     */
    language_mode: 'auto' | 'kz' | 'ru' | 'en';
    /**
     * Audio
     */
    audio: Blob | File;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * History
     */
    history?: Array<ChatMessage> | null;
    /**
     * Page Text
     */
    page_text?: string;
    /**
     * Elements
     */
    elements?: string;
    /**
     * Page Url
     */
    page_url?: string | null;
    /**
     * Screen Label
     */
    screen_label?: string | null;
    /**
     * Screen Fingerprint
     */
    screen_fingerprint?: string | null;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Action
     */
    action?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Client
 */
export type Client = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Public Id
     */
    public_id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Allowed Domains
     */
    allowed_domains: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Admin Key Hash
     */
    admin_key_hash?: string | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * ClientDomainMetrics
 */
export type ClientDomainMetrics = {
    /**
     * Domain
     */
    domain: string;
    /**
     * Tokens
     */
    tokens: number;
    /**
     * Cost
     */
    cost: number;
    /**
     * Traces
     */
    traces: number;
};

/**
 * ClientMetrics
 */
export type ClientMetrics = {
    /**
     * Totalcost
     */
    totalCost: number;
    /**
     * Totaltokens
     */
    totalTokens: number;
    /**
     * Totaltraces
     */
    totalTraces: number;
    /**
     * Details
     */
    details: Array<ClientDomainMetrics>;
};

/**
 * ClientRegisterRequest
 */
export type ClientRegisterRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Domains
     */
    domains: string;
};

/**
 * ClientUpdate
 */
export type ClientUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Domains
     */
    domains?: string | null;
};

/**
 * ConfirmRequest
 */
export type ConfirmRequest = {
    /**
     * Label
     */
    label: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * DiscoverRequest
 */
export type DiscoverRequest = {
    /**
     * Fingerprint
     */
    fingerprint: string;
    /**
     * Tokens
     */
    tokens?: Array<string>;
    /**
     * Page Url
     */
    page_url?: string | null;
};

/**
 * DiscoverResponse
 */
export type DiscoverResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Is Trained
     */
    is_trained: boolean;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ExecuteRequest
 */
export type ExecuteRequest = {
    /**
     * Request Id
     */
    request_id: string;
    step: ActionStep;
    /**
     * Is Final
     */
    is_final?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MatchScreenRequest
 */
export type MatchScreenRequest = {
    /**
     * Fingerprint
     */
    fingerprint: string;
};

/**
 * MatchScreenResponse
 */
export type MatchScreenResponse = {
    /**
     * Matched
     */
    matched: boolean;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * PlanRequest
 */
export type PlanRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Goal
     */
    goal: string;
    /**
     * Elements Context
     */
    elements_context?: string;
};

/**
 * SttTranscriptionResponse
 */
export type SttTranscriptionResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Provider
     */
    provider: 'kz' | 'generic';
    /**
     * Detected Language
     */
    detected_language?: string | null;
};

/**
 * SuggestNameRequest
 */
export type SuggestNameRequest = {
    /**
     * Tokens
     */
    tokens: Array<string>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WidgetLoginData = {
    body: AdminKeyLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login/widget';
};

export type WidgetLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WidgetLoginError = WidgetLoginErrors[keyof WidgetLoginErrors];

export type WidgetLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyWidgetTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login/widget/verify';
};

export type VerifyWidgetTokenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/users/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/users/';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyTokenResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyTokenResponse = VerifyTokenResponses[keyof VerifyTokenResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/status';
};

export type GetStatusResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type RegisterClientData = {
    body: ClientRegisterRequest;
    path?: never;
    query?: never;
    url: '/clients/register';
};

export type RegisterClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterClientError = RegisterClientErrors[keyof RegisterClientErrors];

export type RegisterClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/my';
};

export type GetMyClientsResponses = {
    /**
     * Response Get My Clients
     *
     * Successful Response
     */
    200: Array<Client>;
};

export type GetMyClientsResponse = GetMyClientsResponses[keyof GetMyClientsResponses];

export type DeleteClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type DeleteClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors];

export type DeleteClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateClientData = {
    body: ClientUpdate;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type UpdateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors];

export type UpdateClientResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GenerateAdminKeyData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}/keys';
};

export type GenerateAdminKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAdminKeyError = GenerateAdminKeyErrors[keyof GenerateAdminKeyErrors];

export type GenerateAdminKeyResponses = {
    /**
     * Successful Response
     */
    200: AdminKeyDisplay;
};

export type GenerateAdminKeyResponse = GenerateAdminKeyResponses[keyof GenerateAdminKeyResponses];

export type GetAdminKeyStatusData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: string;
    };
    query?: never;
    url: '/clients/{client_id}/keys/status';
};

export type GetAdminKeyStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdminKeyStatusError = GetAdminKeyStatusErrors[keyof GetAdminKeyStatusErrors];

export type GetAdminKeyStatusResponses = {
    /**
     * Successful Response
     */
    200: AdminKeyStatus;
};

export type GetAdminKeyStatusResponse = GetAdminKeyStatusResponses[keyof GetAdminKeyStatusResponses];

export type GetMyMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/my/metrics';
};

export type GetMyMetricsResponses = {
    /**
     * Successful Response
     */
    200: ClientMetrics;
};

export type GetMyMetricsResponse = GetMyMetricsResponses[keyof GetMyMetricsResponses];

export type ChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/v1/chat';
};

export type ChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatError = ChatErrors[keyof ChatErrors];

export type ChatResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatResponse2 = ChatResponses[keyof ChatResponses];

export type FixA11yMarkupData = {
    body: A11yFixRequest;
    path?: never;
    query?: never;
    url: '/v1/widget/a11y/fix';
};

export type FixA11yMarkupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixA11yMarkupError = FixA11yMarkupErrors[keyof FixA11yMarkupErrors];

export type FixA11yMarkupResponses = {
    /**
     * Response Fix A11Y Markup
     *
     * Successful Response
     */
    200: Array<A11yPatch>;
};

export type FixA11yMarkupResponse = FixA11yMarkupResponses[keyof FixA11yMarkupResponses];

export type SimplifyA11yTextData = {
    body: A11ySimplifyRequest;
    path?: never;
    query?: never;
    url: '/v1/widget/a11y/simplify';
};

export type SimplifyA11yTextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SimplifyA11yTextError = SimplifyA11yTextErrors[keyof SimplifyA11yTextErrors];

export type SimplifyA11yTextResponses = {
    /**
     * Successful Response
     */
    200: A11ySimplifyResponse;
};

export type SimplifyA11yTextResponse = SimplifyA11yTextResponses[keyof SimplifyA11yTextResponses];

export type TranscribeAudioData = {
    body: BodyTranscribeAudio;
    path?: never;
    query?: never;
    url: '/v1/stt/transcribe';
};

export type TranscribeAudioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranscribeAudioError = TranscribeAudioErrors[keyof TranscribeAudioErrors];

export type TranscribeAudioResponses = {
    /**
     * Successful Response
     */
    200: SttTranscriptionResponse;
};

export type TranscribeAudioResponse = TranscribeAudioResponses[keyof TranscribeAudioResponses];

export type DiscoverScreenData = {
    body: DiscoverRequest;
    path?: never;
    query?: never;
    url: '/v1/training/discover';
};

export type DiscoverScreenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DiscoverScreenError = DiscoverScreenErrors[keyof DiscoverScreenErrors];

export type DiscoverScreenResponses = {
    /**
     * Successful Response
     */
    200: DiscoverResponse;
};

export type DiscoverScreenResponse = DiscoverScreenResponses[keyof DiscoverScreenResponses];

export type ListScreensBearerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Is Draft
         */
        is_draft?: boolean | null;
    };
    url: '/v1/training/screens';
};

export type ListScreensBearerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListScreensBearerError = ListScreensBearerErrors[keyof ListScreensBearerErrors];

export type ListScreensBearerResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfirmScreenBearerData = {
    body: ConfirmRequest;
    path: {
        /**
         * Screen Id
         */
        screen_id: string;
    };
    query?: never;
    url: '/v1/training/confirm/{screen_id}';
};

export type ConfirmScreenBearerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmScreenBearerError = ConfirmScreenBearerErrors[keyof ConfirmScreenBearerErrors];

export type ConfirmScreenBearerResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MatchScreenData = {
    body: MatchScreenRequest;
    path?: never;
    query?: never;
    url: '/v1/training/match-screen';
};

export type MatchScreenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MatchScreenError = MatchScreenErrors[keyof MatchScreenErrors];

export type MatchScreenResponses = {
    /**
     * Successful Response
     */
    200: MatchScreenResponse;
};

export type MatchScreenResponse2 = MatchScreenResponses[keyof MatchScreenResponses];

export type SuggestNameData = {
    body: SuggestNameRequest;
    path?: never;
    query?: never;
    url: '/v1/training/suggest-name';
};

export type SuggestNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SuggestNameError = SuggestNameErrors[keyof SuggestNameErrors];

export type SuggestNameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DashboardGetClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/training/dashboard/clients';
};

export type DashboardGetClientsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DashboardListScreensData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Client Public Id
         */
        client_public_id?: string | null;
        /**
         * Is Draft
         */
        is_draft?: boolean | null;
    };
    url: '/v1/training/dashboard/screens';
};

export type DashboardListScreensErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DashboardListScreensError = DashboardListScreensErrors[keyof DashboardListScreensErrors];

export type DashboardListScreensResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DashboardConfirmScreenData = {
    body: ConfirmRequest;
    path: {
        /**
         * Screen Id
         */
        screen_id: string;
    };
    query?: never;
    url: '/v1/training/dashboard/confirm/{screen_id}';
};

export type DashboardConfirmScreenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DashboardConfirmScreenError = DashboardConfirmScreenErrors[keyof DashboardConfirmScreenErrors];

export type DashboardConfirmScreenResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GeneratePlanData = {
    body: PlanRequest;
    path?: never;
    query?: never;
    url: '/v1/agent/plan';
};

export type GeneratePlanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneratePlanError = GeneratePlanErrors[keyof GeneratePlanErrors];

export type GeneratePlanResponses = {
    /**
     * Successful Response
     */
    200: ActionPlan;
};

export type GeneratePlanResponse = GeneratePlanResponses[keyof GeneratePlanResponses];

export type ExecuteStepData = {
    body: ExecuteRequest;
    path?: never;
    query?: {
        /**
         * Confirm
         */
        confirm?: boolean;
    };
    url: '/v1/agent/execute';
};

export type ExecuteStepErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteStepError = ExecuteStepErrors[keyof ExecuteStepErrors];

export type ExecuteStepResponses = {
    /**
     * Response Execute Step
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteStepResponse = ExecuteStepResponses[keyof ExecuteStepResponses];
